### ISSUE TITLE
Unable to build packages with TransferSqlServer Object tasks or SqlServerManagement Connections 

### ISSUE THREAD

**Issue by jalley3** [varigence/BimlPit#141]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead go to https://varigence.com/Forums?forumName=Biml or email support@varigence.com
[ ] Other... Please describe:
</code></pre>

## Current behavior

You cannot currently build a package that uses the SqlServerManagement Connections for TransferSqlServerObjects Tasks. When you attempt to, you get the following compiler error message:

EmitSsis. Internal Compiler Error: Workflow EmitSsis contains fatal errors. Phase execution halted. For assistance, please send Biml Compiler error messages to support@varigence.com. See other errors for more information. Exception type: NullReferenceException

 

## Minimal reproduction of the problem with instructions

[sqlservermanagementrepro.txt](https://github.com/varigence/BimlPit/files/3917638/sqlservermanagementrepro.txt)

The above biml code reproduces the issue.

## Environment

<pre><code>
BimlExpress version: 5.0.6418.0

Visual Studio Version:

- [ ] 2005
- [ ] 2008
- [ ] 2010
- [ ] 2012
- [ ] 2013
- [ ] 2015
- [x ] 2017

Target SSIS Version:

- [ ] 2005
- [ ] 2008
- [ ] 2008 R2
- [ ] 2012
- [ ] 2014
- [ ] 2016
- [x ] 2017

Others:

</code></pre>

**Comment by jalley3** [comment]
Fixed as of commit 155bcb29

**Comment by mlampeitl2** [comment]
The bug is probably not fixed.

Validating Biml
1/1 Emitting Project Package.dtproj.
1/1 Emitting Package Package.
EmitSsis. Internal Compiler Error: Workflow EmitSsis contains fatal errors. Phase execution halted. For assistance, please send Biml Compiler error messages to support@varigence.com. See other errors for more information. Exception type: NullReferenceException

Here the tag:

                <TransferSqlServerObjects Name="Transfer SQL Server Objects Task" DestinationConnectionName=".\SQL_C" DestinationDatabase="test" SourceConnectionName=".\SQL_C" SourceDatabase="test2">
                    <Tables>
                    <Table>[itf].[personne]</Table>                    </Tables>
                </TransferSqlServerObjects>


Using VS2019/SSIS2019

Varigence BimlExpress 5.0 (32-bit)
Build 5.0.64108.0
Features and Bundles: No features or bundles have been authorized
Plugins: No plugins have been loaded
